### ISSUE TITLE
Conference settings

### ISSUE THREAD

**Issue by l-heimann** [bufak-wiwi/konfetti#10]
- Viewing and editing information texts, application phases etc.
- Generating and downloading application codes
- Exporting information of all conference applications

**Comment by mobun** [comment]
# Functions
* Generate conference auth codes
* Create CSV export
** Auth Codes
*** FS and additional
** Badges (inkl. Workshop, Rooms etc.)
** Workshops
** All conference applications


# Endpoints

* Get CSV export
* Update specific application
* Update all selected applications
* Update settings
** Different application phases
** Conference texts and links
